### ISSUE TITLE
Automatic Gridware initialisation when no app-manager exists

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware-handlers#12]
Gridware no longer automatically initialises by default, so when deploying an environment which contains no application manager appliance - no Gridware will be available to the environment. 

There should be some way of setting no application manager, thus the login node configuring/sharing to its nodes.

**Comment by mjtko** [comment]
I think before we are able to solve this we need to give more consideration to the application manager use cases and how the application manager hooks in to the cluster.

**Comment by mjtko** [comment]
As of ad3a2c5, enabling the `cluster-gridware` handler now automatically initializes the `/opt/gridware` tree (or whatever path is set in `/opt/clusterware/etc/gridware.rc`).
