### ISSUE TITLE
Reduce duplication between scheduler autoscaling handling

### ISSUE THREAD

**Issue by bobwhitelock** [alces-software/clusterware-handlers#36]
There is a lot of duplication between the autoscaling handling currently for cluster-sge and cluster-slurm, and this will likely continue as other schedulers are added as it is mostly scheduler-independent.

I've documented parts I noticed were identical or could be easily adapted to extract identical functions while making the cluster-slurm handler, to try and help with this.

**Comment by mjtko** [comment]
Closed via #35.
