### ISSUE TITLE
Last node can get stuck unable to be scheduled on in certain situation

### ISSUE THREAD

**Issue by bobwhitelock** [alces-software/clusterware-handlers#37]
For both SGE and Slurm, when attempting to scale in a cluster which has the minimum number of compute nodes for its auto-scaling group and there are no pending or running jobs, the autoscaler will detect that it needs to scale in, attempt to do so, but then fail as the last node cannot be shut down. We then do not detect this and never re-enable the node's queue, leaving it stuck unusable until manual action is taken.

**Comment by mjtko** [comment]
Closed via #35.
