### ISSUE TITLE
clusterable-aws-compat: route53 hosted zone name

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware-handlers#5]
Currently looks for zone `cluster.` - should be reconfigurable via user data to support multiple hosted zones on the same AWS account.

**Comment by mjtko** [comment]
Can now specify the zone name by supplying a `aws_zone_name` key in the user data.

**Comment by mjtko** [comment]
NB. the `aws_zone_name` value should not include a trailing `.` character.
