### ISSUE TITLE
TORQUE Scheduler not autoscaling

### ISSUE THREAD

**Issue by andrewprovis** [alces-software/clusterware-handlers#75]
I've come across an issue where the TORQUE scheduler is not autoscaling. It appears that the instance type name of my compute nodes (c4.large in this case) is not changing the "." to a "_" so generates a bash variable with a dot in it.

**Comment by jamesremuscat** [comment]
Specifically: the value provided for `$default_queue` needs to apply a transformation. From the SGE equivalent:

```
puts "gridscheduler_queue_#{k.gsub(/[-\.]/, "_")}_cores_req=#{v[:cores]}"
```

We're missing the `gsub` from the Torque, OpenLava and PBSPro implementations e.g. this commit https://github.com/alces-software/clusterware-services/commit/64b9471fde9f0c50dd93e15fc053d6ed04625396 was insufficient.

This issue will mean that autoscaling does not work for these three schedulers if the default queue name contains one or more periods or hyphens. I'll draw up a fix.
